/* Generated By:JavaCC: Do not edit this line. DataToProgramConstants.java */
package src.datatoprogram;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DataToProgramConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int READ = 5;
  /** RegularExpression Id. */
  int WRITE = 6;
  /** RegularExpression Id. */
  int ASSIGN = 7;
  /** RegularExpression Id. */
  int WHILE = 8;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int QUOTE = 10;
  /** RegularExpression Id. */
  int NIL = 11;
  /** RegularExpression Id. */
  int CONS = 12;
  /** RegularExpression Id. */
  int HD = 13;
  /** RegularExpression Id. */
  int TL = 14;
  /** RegularExpression Id. */
  int VAR = 15;
  /** RegularExpression Id. */
  int NUM = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"read\"",
    "\"write\"",
    "\":=\"",
    "\"while\"",
    "\"if\"",
    "\"quote\"",
    "\"nil\"",
    "\"cons\"",
    "\"hd\"",
    "\"tl\"",
    "\"var\"",
    "<NUM>",
    "\"[\"",
    "\",\"",
    "\"]\"",
  };

}
