/* Generated By:JJTree: Do not edit this line. ASTDefaultCase.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.interpreter;

public
class ASTDefaultCase extends SimpleNode {
  public ASTDefaultCase(int id) {
    super(id);
  }

  public ASTDefaultCase(ProgramParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ProgramParserVisitor visitor, Object data) throws InterpreterException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d0f06d31562f6831a25f7b27170ac480 (do not edit this line) */
