/* Generated By:JJTree&JavaCC: Do not edit this line. ProgramParserConstants.java */
package src.interpreter;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProgramParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int READ = 7;
  /** RegularExpression Id. */
  int WRITE = 8;
  /** RegularExpression Id. */
  int ASSIGN = 9;
  /** RegularExpression Id. */
  int WHILE = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int ELSE = 12;
  /** RegularExpression Id. */
  int CONS = 13;
  /** RegularExpression Id. */
  int NIL = 14;
  /** RegularExpression Id. */
  int HD = 15;
  /** RegularExpression Id. */
  int TL = 16;
  /** RegularExpression Id. */
  int SWITCH = 17;
  /** RegularExpression Id. */
  int CASE = 18;
  /** RegularExpression Id. */
  int DEFAULTCASE = 19;
  /** RegularExpression Id. */
  int DOT = 20;
  /** RegularExpression Id. */
  int ATOM = 21;
  /** RegularExpression Id. */
  int BOOLEAN = 22;
  /** RegularExpression Id. */
  int VAR = 23;
  /** RegularExpression Id. */
  int NUM = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"read\"",
    "\"write\"",
    "\":=\"",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\"cons\"",
    "\"nil\"",
    "\"hd\"",
    "\"tl\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\".\"",
    "<ATOM>",
    "<BOOLEAN>",
    "<VAR>",
    "<NUM>",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"<\"",
    "\">\"",
    "\":\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
