/* Generated By:JavaCC: Do not edit this line. ProgramParserTreeConstants.java Version 6.0_1 */
package src.interpreter;

public interface ProgramParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTPROGNAME = 2;
  public int JJTINPUT = 3;
  public int JJTOUTPUT = 4;
  public int JJTBLOCK = 5;
  public int JJTMACRO = 6;
  public int JJTASSIGN = 7;
  public int JJTWHILE = 8;
  public int JJTIF = 9;
  public int JJTSWITCH = 10;
  public int JJTCASE = 11;
  public int JJTEXPRLIST = 12;
  public int JJTDEFAULTCASE = 13;
  public int JJTEQUAL = 14;
  public int JJTNIL = 15;
  public int JJTCONS = 16;
  public int JJTATOM = 17;
  public int JJTHD = 18;
  public int JJTTL = 19;
  public int JJTNUM = 20;
  public int JJTBOOL = 21;
  public int JJTVAR = 22;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "progname",
    "input",
    "output",
    "Block",
    "Macro",
    "Assign",
    "While",
    "If",
    "Switch",
    "Case",
    "ExprList",
    "DefaultCase",
    "Equal",
    "nil",
    "Cons",
    "atom",
    "Hd",
    "Tl",
    "num",
    "bool",
    "var",
  };
}
/* JavaCC - OriginalChecksum=8e0309e0c50164892b60326b5d02ced6 (do not edit this line) */
