/* Generated By:JavaCC: Do not edit this line. InputParserConstants.java */
package src.inputparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface InputParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASSIGN = 5;
  /** RegularExpression Id. */
  int WHILE = 6;
  /** RegularExpression Id. */
  int IF = 7;
  /** RegularExpression Id. */
  int QUOTE = 8;
  /** RegularExpression Id. */
  int NIL = 9;
  /** RegularExpression Id. */
  int VAR = 10;
  /** RegularExpression Id. */
  int CONS = 11;
  /** RegularExpression Id. */
  int HD = 12;
  /** RegularExpression Id. */
  int TL = 13;
  /** RegularExpression Id. */
  int NUM = 14;
  /** RegularExpression Id. */
  int BOOLEAN = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\":=\"",
    "\"while\"",
    "\"if\"",
    "\"quote\"",
    "\"nil\"",
    "\"var\"",
    "\"cons\"",
    "\"hd\"",
    "\"tl\"",
    "<NUM>",
    "<BOOLEAN>",
    "\"[\"",
    "\",\"",
    "\"]\"",
    "\"<\"",
    "\".\"",
    "\">\"",
    "\"(\"",
    "\")\"",
  };

}
